# Generated by Django 4.2.28 on 2026-06-05 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('body', models.TextField(verbose_name='Contenu (HTML)')),
                ('recipients', models.TextField(verbose_name='Destinataires')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Envois réussis')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Envois échoués')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composed_emails', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Email envoyé',
                'verbose_name_plural': 'Emails envoyés',
                'ordering': ['-created_at'],
            },
        ),
    ]
