# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé de la tranche')),
                ('order_number', models.IntegerField(verbose_name='Ordre de la tranche')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la tranche')),
                ('due_date', models.DateField(verbose_name='À payer avant le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='academic.academicyear', verbose_name='Année académique')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='academic.level', verbose_name="Niveau d'étude")),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='academic.program', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Tranche de paiement',
                'verbose_name_plural': 'Tranches de paiement',
                'ordering': ['program__name', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('inscription', "Frais d'inscription"), ('frais_ratrappage', 'Frais de ratrappage'), ('frais_scolarite', 'Frais de scolarité'), ('frais_stage', 'Frais de stage'), ('frais_soutenance', 'Frais de soutenance'), ('autre', 'Autre')], default='frais_scolarite', max_length=20, verbose_name='Catégorie de paiement')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('payment_date', models.DateTimeField(verbose_name='Date de paiement')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de reçu')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transaction')),
                ('source', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Source du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academic.academicyear', verbose_name='Année académique')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentinstallment', verbose_name='Tranche de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
