# Generated by Django 4.2.28 on 2026-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant partagé par les paiements créés ensemble (ex. règlement couvrant plusieurs tranches).', max_length=100, null=True, verbose_name='Référence de groupe'),
        ),
    ]
