# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('dossier_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de dossier')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('date_naiss', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Examinée & Approuvée'), ('abandoned', 'Abandonné'), ('rejected', 'Rejetée'), ('registered', 'Inscrit')], default='pending', max_length=50, verbose_name='Statut de pré-inscription')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Genre')),
                ('lang', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=50, verbose_name='Langue')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'inscription")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('last_registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Date dernière inscription')),
                ('specialite_souhaitee_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité souhaitée 1')),
                ('specialite_souhaitee_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité souhaitée 2')),
                ('specialite_souhaitee_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité souhaitée 3')),
                ('external_password_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Mot de passe pour consultation externe')),
                ('external_password_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du mot de passe')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo de profil')),
                ('godfather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.godfather', verbose_name='Parrain')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-created_at', 'lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='StudentMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom complet de la mère')),
                ('mother_live_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de résidence de la mère')),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la mère')),
                ('mother_occupation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession de la mère')),
                ('mother_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone de la mère')),
                ('father_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom complet du père')),
                ('father_live_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de résidence du père')),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du père')),
                ('father_occupation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession du père')),
                ('father_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone du père')),
                ('original_country', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('original_region', models.CharField(blank=True, max_length=100, null=True, verbose_name="Région d'origine")),
                ('original_department', models.CharField(blank=True, max_length=100, null=True, verbose_name="Département d'origine")),
                ('original_district', models.CharField(blank=True, max_length=100, null=True, verbose_name="District d'origine")),
                ('residence_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de résidence')),
                ('residence_quarter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier de résidence')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Dossier complet')),
                ('is_online_registration', models.BooleanField(default=False, verbose_name='Inscription en ligne')),
                ('preuve_baccalaureat', models.FileField(blank=True, help_text='Copie du document attestant la réussite du baccalauréat ou équivalent (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/baccalaureat/', verbose_name="Preuve d'obtention du baccalauréat")),
                ('acte_naissance', models.FileField(blank=True, help_text="Photocopie certifiée conforme de l'acte de naissance (PNG/JPG/PDF, max 5Mo)", null=True, upload_to='documents/inscription/acte_naissance/', verbose_name="Photocopie certifiée de l'acte de naissance")),
                ('releve_notes_last_class', models.FileField(blank=True, help_text='Photocopie du relevé de notes de la dernière classe fréquentée (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/releve_notes/', verbose_name='Relevé de notes de la dernière classe fréquentée')),
                ('justificatif_dernier_diplome', models.FileField(blank=True, help_text='Photocopie du justificatif du dernier diplôme obtenu (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/justificatif_diplome/', verbose_name='Justificatif du dernier diplôme obtenu')),
                ('decharge_equivalence', models.FileField(blank=True, help_text="Photocopie de la décharge de la demande d'équivalence pour les diplômes étrangers (PNG/JPG/PDF, max 5Mo)", null=True, upload_to='documents/inscription/decharge_equivalence/', verbose_name="Décharge de la demande d'équivalence pour les diplômes étrangers")),
                ('bulletins_terminale', models.FileField(blank=True, help_text='Photocopie des bulletins de notes de la classe de terminale (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/bulletins/', verbose_name='Bulletins de la classe de terminale')),
                ('releve_notes_master1', models.FileField(blank=True, help_text='Relevé de notes du Master 1 ou de tout autre diplôme équivalent (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/releve_master1/', verbose_name='Relevé de notes du Master 1 ou de tout autre diplôme équivalent')),
                ('photocopie_bts_hnd', models.FileField(blank=True, help_text='Photocopie du BTS, HND ou de tout autre diplôme équivalent (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/bts_hnd/', verbose_name='Photocopie du BTS, HND ou de tout autre diplôme équivalent')),
                ('certificat_nationalite', models.FileField(blank=True, help_text='Photocopie certifiée conforme du certificat de nationalité (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/certificat_nationalite/', verbose_name='Certificat de nationalité')),
            ],
            options={
                'verbose_name': 'Métadonnées Étudiant',
                'verbose_name_plural': 'Métadonnées Étudiants',
            },
        ),
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False, verbose_name="Niveau actuel de l'étudiant?")),
                ('is_registered', models.BooleanField(default=False, verbose_name="L'étudiant est-il officiellement inscrit à ce niveau?")),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'inscription")),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='academic.academicyear', verbose_name='Année académique')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='academic.level', verbose_name='Niveau')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_levels', to='academic.speciality', verbose_name="Spécialité de l'étudiant")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='students.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Niveau Étudiant',
                'verbose_name_plural': 'Niveaux Étudiants',
                'ordering': ['student__lastname', 'student__firstname'],
                'unique_together': {('student', 'level', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.studentmetadata', verbose_name='Métadonnées'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.program', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.school', verbose_name='École fréquentée'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_start_level', to='academic.level', verbose_name="Niveau d'entrée"),
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('student_card', "Carte d'étudiant"), ('transcript', 'Relevé de notes'), ('diploma', 'Diplôme'), ('certificate', 'Certificat de scolarité'), ('registration_certificate', 'CERTIFICAT D’INSCRIPTION')], max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('status', models.CharField(choices=[('available', 'Non déchargé'), ('withdrawn', 'Déchargé'), ('returned', 'Retourné'), ('lost', 'Perdu')], default='available', max_length=50)),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_documents', to='students.studentlevel')),
            ],
            options={
                'verbose_name': 'documents officiel',
                'verbose_name_plural': 'documents officiels',
                'ordering': ['-created_at', 'student_level__student__lastname', 'student_level__student__firstname'],
            },
        ),
    ]
