# Generated by Django 4.2.28 on 2026-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date dernière connexion'),
        ),
    ]
