# Generated by Django 5.2.1 on 2025-05-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_live_city', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(max_length=100)),
                ('lang', models.CharField(default='fr', max_length=50)),
                ('original_region', models.CharField(blank=True, max_length=100, null=True)),
                ('original_department', models.CharField(blank=True, max_length=100, null=True)),
                ('original_district', models.CharField(blank=True, max_length=100, null=True)),
                ('residence_city', models.CharField(blank=True, max_length=100, null=True)),
                ('residence_quarter', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('father_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Métadonnées Étudiant',
                'verbose_name_plural': 'Métadonnées Étudiants',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='method_type',
        ),
        migrations.AlterField(
            model_name='student',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.studentmetadata'),
        ),
    ]
