# Generated by Django 4.2.28 on 2026-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Doit changer son mot de passe à la prochaine connexion'),
        ),
    ]
