# Generated by Django 5.2.1 on 2025-06-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentmetadata_remove_student_method_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
