# Generated by Django 5.2.1 on 2025-06-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0003_remove_student_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentlevel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentlevel',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='studentlevel',
            unique_together={('student', 'level', 'academic_year')},
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('student_card', "Carte d'étudiant"), ('transcript', 'Relevé de notes'), ('diploma', 'Diplôme'), ('certificate', 'Certificat de scolarité')], max_length=100)),
                ('status', models.CharField(choices=[('available', 'Non déchargé'), ('withdrawn', 'Déchargé'), ('lost', 'Perdu')], default='available', max_length=50)),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_documents', to='students.studentlevel')),
            ],
            options={
                'verbose_name': 'documents officiel',
                'verbose_name_plural': 'documents officiels',
            },
        ),
    ]
