# Generated by Django 5.2.1 on 2025-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentlevel_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialdocument',
            name='student_level',
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_documents', to='students.student'),
        ),
    ]
