# Generated by Django 4.2.28 on 2026-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.AddField(
            model_name='student',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de vérification de l'email"),
        ),
    ]
