# Generated by Django 5.2.1 on 2025-06-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_officialdocument_student_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialdocument',
            name='student',
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='student_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_documents', to='students.studentlevel'),
        ),
    ]
