# Generated by Django 4.2.28 on 2026-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_email_verified_student_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='preinscription_step',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Étape de pré-inscription atteinte'),
        ),
    ]
