# Generated by Django 5.2.1 on 2025-06-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_officialdocument_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlevel',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
