# Generated by Django 4.2.28 on 2026-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_preinscription_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmetadata',
            name='acte_naissance',
            field=models.FileField(blank=True, help_text="Photocopie certifiée conforme de l'acte de naissance (PNG/JPG/JPEG/PDF, max 5Mo)", null=True, upload_to='documents/inscription/acte_naissance/', verbose_name="Photocopie certifiée de l'acte de naissance"),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='bulletins_terminale',
            field=models.FileField(blank=True, help_text='Photocopie des bulletins de notes de la classe de terminale (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/bulletins/', verbose_name='Bulletins de la classe de terminale'),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='certificat_nationalite',
            field=models.FileField(blank=True, help_text='Photocopie certifiée conforme du certificat de nationalité (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/certificat_nationalite/', verbose_name='Certificat de nationalité'),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='decharge_equivalence',
            field=models.FileField(blank=True, help_text="Photocopie de la décharge de la demande d'équivalence pour les diplômes étrangers (PNG/JPG/JPEG/PDF, max 5Mo)", null=True, upload_to='documents/inscription/decharge_equivalence/', verbose_name="Décharge de la demande d'équivalence pour les diplômes étrangers"),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='justificatif_dernier_diplome',
            field=models.FileField(blank=True, help_text='Photocopie du justificatif du dernier diplôme obtenu (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/justificatif_diplome/', verbose_name='Justificatif du dernier diplôme obtenu'),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='photocopie_bts_hnd',
            field=models.FileField(blank=True, help_text='Photocopie du BTS, HND ou de tout autre diplôme équivalent (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/bts_hnd/', verbose_name='Photocopie du BTS, HND ou de tout autre diplôme équivalent'),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='preuve_baccalaureat',
            field=models.FileField(blank=True, help_text='Copie du document attestant la réussite du baccalauréat ou équivalent (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/baccalaureat/', verbose_name="Preuve d'obtention du baccalauréat"),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='releve_notes_last_class',
            field=models.FileField(blank=True, help_text='Photocopie du relevé de notes de la dernière classe fréquentée (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/releve_notes/', verbose_name='Relevé de notes de la dernière classe fréquentée'),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='releve_notes_master1',
            field=models.FileField(blank=True, help_text='Relevé de notes du Master 1 ou de tout autre diplôme équivalent (PNG/JPG/JPEG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/releve_master1/', verbose_name='Relevé de notes du Master 1 ou de tout autre diplôme équivalent'),
        ),
    ]
