# Generated by Django 5.2.1 on 2025-06-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentlevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlevel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
