# Generated by Django 5.2.1 on 2025-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_created_at_student_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lang',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=50),
        ),
    ]
