# Generated by Django 5.2.1 on 2025-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_alter_student_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmetadata",
            name="is_complete",
            field=models.BooleanField(default=True, verbose_name="Dossier complet"),
        ),
    ]
