# Generated by Django 5.2.1 on 2025-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_studentmetadata_is_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentmetadata",
            old_name="last_alias",
            new_name="father_live_city",
        ),
        migrations.RenameField(
            model_name="studentmetadata",
            old_name="country",
            new_name="original_country",
        ),
        migrations.RemoveField(
            model_name="studentmetadata",
            name="lang",
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="father_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="father_occupation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="father_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="mother_full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentmetadata",
            name="father_full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
