# Generated by Django 5.2.1 on 2025-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0012_rename_last_alias_studentmetadata_father_live_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_naiss",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
    ]
