# Generated by Django 5.2.1 on 2025-07-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_alter_student_date_naiss"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentlevel",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Niveau actuel de l'étudiant?"
            ),
        ),
    ]
