# Generated by Django 5.2.1 on 2025-07-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentlevel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmetadata',
            name='acte_naissance',
            field=models.FileField(blank=True, help_text="Photocopie certifiée conforme de l'acte de naissance (PNG/JPG/PDF, max 5Mo)", null=True, upload_to='documents/inscription/acte_naissance/', verbose_name="Photocopie certifiée de l'acte de naissance"),
        ),
        migrations.AddField(
            model_name='studentmetadata',
            name='bulletins_terminale',
            field=models.FileField(blank=True, help_text='Photocopie des bulletins de notes de la classe de terminale (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/bulletins/', verbose_name='Bulletins de la classe de terminale'),
        ),
        migrations.AddField(
            model_name='studentmetadata',
            name='preuve_baccalaureat',
            field=models.FileField(blank=True, help_text='Copie du document attestant la réussite du baccalauréat ou équivalent (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/baccalaureat/', verbose_name="Preuve d'obtention du baccalauréat"),
        ),
        migrations.AddField(
            model_name='studentmetadata',
            name='releve_notes_bac',
            field=models.FileField(blank=True, help_text='Photocopie certifiée conforme du relevé des notes du baccalauréat (PNG/JPG/PDF, max 5Mo)', null=True, upload_to='documents/inscription/releve_notes/', verbose_name='Relevé des notes du Baccalauréat'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'inscription"),
        ),
    ]
