# Generated by Django 5.2.1 on 2025-07-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_studentmetadata_acte_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='external_password_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création du mot de passe'),
        ),
        migrations.AddField(
            model_name='student',
            name='external_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Mot de passe pour consultation externe'),
        ),
    ]
