# Generated by Django 5.2.1 on 2025-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_external_password_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocument',
            name='returned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officialdocument',
            name='status',
            field=models.CharField(choices=[('available', 'Non déchargé'), ('withdrawn', 'Déchargé'), ('returned', 'Retourné'), ('lost', 'Perdu')], default='available', max_length=50),
        ),
    ]
