# Generated by Django 5.2.1 on 2025-07-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_speciality_program'),
        ('students', '0017_add_returned_status_and_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('abandoned', 'abandonné'), ('rejected', 'Rejetée')], max_length=50, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total dû')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant restant')),
                ('status', models.CharField(choices=[('up_to_date', 'À jour'), ('partial', 'Paiement partiel'), ('overdue', 'En retard'), ('blocked', 'Bloqué')], default='up_to_date', max_length=20, verbose_name='Statut de paiement')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Dernière date de paiement')),
                ('documents_blocked', models.BooleanField(default=False, verbose_name='Documents bloqués')),
                ('blocking_reason', models.TextField(blank=True, null=True, verbose_name='Raison du blocage')),
                ('has_payment_plan', models.BooleanField(default=False, verbose_name='Échéancier personnalisé')),
                ('payment_plan_details', models.TextField(blank=True, null=True, verbose_name="Détails de l'échéancier")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='academic.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='students.student')),
            ],
            options={
                'verbose_name': 'Statut de paiement',
                'verbose_name_plural': 'Statuts de paiement',
                'ordering': ['-academic_year__start_at', 'student__lastname', 'student__firstname'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
