# Generated by Django 4.2.28 on 2026-05-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0005_level_cycle'),
        ('lecturers', '0002_remove_lecturer_favorite_subjects_lecturer_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField(default=0, verbose_name="Années d'expérience dans l'enseignement de cette matière")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='lecturers/subjects/proofs/', verbose_name="Justificatif ou preuve d'expérience")),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_subjects', to='lecturers.lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_subjects', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Matière enseignée',
                'verbose_name_plural': 'Matières enseignées',
                'unique_together': {('lecturer', 'subject')},
            },
        ),
    ]
