# Generated by Django 4.2.28 on 2026-05-21 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_remove_lecturer_favorite_subjects_lecturer_cv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0005_level_cycle'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturersubject',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='practice_experience_years',
            field=models.IntegerField(default=0, verbose_name="Années d'expérience dans la pratique de cette discipline"),
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='teaching_experience_years',
            field=models.IntegerField(default=0, verbose_name="Années d'expérience dans l'enseignement de cette discipline"),
        ),
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé pour enseigner ce cours')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_courses', to='academic.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_courses', to='lecturers.lecturer')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_courses', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Cours enseigné',
                'verbose_name_plural': 'Cours enseignés',
                'unique_together': {('lecturer', 'course')},
            },
        ),
    ]
