# Generated by Django 4.2.28 on 2026-05-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecturers', '0005_lecturer_can_be_resubmitted'),
        ('recruitment', '0002_remove_lecturersubject_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturersubject',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Validée pour enseigner cette matière'),
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.CreateModel(
            name='LecturerRefusalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motif de refus')),
                ('can_be_resubmitted', models.BooleanField(default=False, verbose_name='Resoumission autorisée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du refus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_refusals', to=settings.AUTH_USER_MODEL, verbose_name='Refusé par')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refusal_reasons', to='lecturers.lecturer')),
            ],
            options={
                'verbose_name': 'Motif de refus',
                'verbose_name_plural': 'Motifs de refus',
                'ordering': ['-created_at'],
            },
        ),
    ]
