# Generated by Django 4.2.28 on 2026-06-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_course_course_code'),
        ('lecturers', '0007_lecturer_created_at_lecturer_deleted_at_and_more'),
        ('recruitment', '0003_lecturersubject_is_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturercourse',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='lecturersubject',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='lecturercourse',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('refused', 'Refusée')], default='pending', max_length=20, verbose_name='Statut de validation de ce cours'),
        ),
        migrations.AddField(
            model_name='lecturersubject',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('refused', 'Refusée')], default='pending', max_length=20, verbose_name='Statut de validation de cette matière'),
        ),
        migrations.AlterField(
            model_name='lecturersubject',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_subjects', to='lecturers.lecturer', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='lecturersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_subjects', to='academic.subject', verbose_name='Matière'),
        ),
    ]
