# Generated by Django 4.2.28 on 2026-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_lecturercourse_is_validated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerrefusalreason',
            options={'ordering': ['-created_at'], 'verbose_name': 'Motif de refus de candidature', 'verbose_name_plural': 'Motifs de refus de candidature'},
        ),
        migrations.AlterModelOptions(
            name='lecturersubject',
            options={'verbose_name': "Domaine d'enseignement", 'verbose_name_plural': "Domaines d'enseignement"},
        ),
        migrations.AlterField(
            model_name='lecturerrefusalreason',
            name='reason',
            field=models.TextField(help_text="Indiquez clairement les raisons du refus de la candidature. Cela aidera l'enseignant à comprendre les points à améliorer pour une éventuelle resoumission.", max_length=1000, verbose_name='Motif de refus'),
        ),
    ]
