# Generated by Django 5.2.1 on 2025-07-15 23:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0009_speciality_program'),
        ('schools', '0003_alter_school_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('type_agent', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], max_length=10, verbose_name="Type d'agent")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10, verbose_name='Statut')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Agent de prospection',
                'verbose_name_plural': 'Agents de prospection',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='planifiee', max_length=15, verbose_name='Statut')),
                ('objectif_global', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Objectif global (nombre de prospects)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear', verbose_name='Année académique')),
            ],
            options={
                'verbose_name': 'Campagne de prospection',
                'verbose_name_plural': 'Campagnes de prospection',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('objectif_prospects', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Objectif (nombre de prospects)')),
                ('date_assignation', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'assignation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('agents', models.ManyToManyField(related_name='equipes', to='prospection.agent', verbose_name='Agents')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='prospection.campagne', verbose_name='Campagne')),
                ('chef_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_dirigees', to='prospection.agent', verbose_name="Chef d'équipe")),
                ('etablissement_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Établissement cible')),
            ],
            options={
                'verbose_name': 'Équipe de prospection',
                'verbose_name_plural': 'Équipes de prospection',
                'ordering': ['campagne', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('telephone_pere', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du père')),
                ('telephone_mere', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de la mère')),
                ('date_collecte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de collecte')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('agent_collecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_collectes', to='prospection.agent', verbose_name='Agent collecteur')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='prospection.equipe', verbose_name='Équipe')),
                ('etablissement_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name="Établissement d'origine")),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-date_collecte'],
                'unique_together': {('telephone', 'equipe')},
            },
        ),
    ]
