# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('type_agent', models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], max_length=10, verbose_name="Type d'agent")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('pending', "En attente d'activation")], default='pending', max_length=10, verbose_name='Statut')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('is_active', models.BooleanField(default=False, verbose_name='Compte activé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Agent de prospection',
                'verbose_name_plural': 'Agents de prospection',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='planifiee', max_length=15, verbose_name='Statut')),
                ('objectif_global', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Objectif global (nombre de prospects)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Campagne de prospection',
                'verbose_name_plural': 'Campagnes de prospection',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'équipe")),
                ('zone_assignee', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zone assignée')),
                ('objectif_prospects', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Objectif (nombre de prospects)')),
                ('objectif_equipe', models.PositiveIntegerField(default=0, verbose_name="Objectif de l'équipe")),
                ('date_assignation', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'assignation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Équipe de prospection',
                'verbose_name_plural': 'Équipes de prospection',
                'ordering': ['seance', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProspectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text="Active ou désactive le module de prospection dans l'application", verbose_name='Prospection activée')),
                ('activation_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'activation")),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modifié par')),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'activation/désactivation", null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Configuration Prospection',
                'verbose_name_plural': 'Configuration Prospection',
            },
        ),
        migrations.CreateModel(
            name='SeanceProspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(verbose_name='Date de la séance')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='prospection.campagne', verbose_name='Campagne')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Séance de prospection',
                'verbose_name_plural': 'Séances de prospection',
                'ordering': ['-date_seance'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('telephone_pere', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du père')),
                ('telephone_mere', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de la mère')),
                ('date_collecte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de collecte')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('agent_collecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_collectes', to='prospection.agent', verbose_name='Agent collecteur')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='prospection.equipe', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-date_collecte'],
            },
        ),
    ]
