# Generated by Django 5.2.1 on 2025-07-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text="Active ou désactive le module de prospection dans l'application", verbose_name='Prospection activée')),
                ('activation_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'activation")),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modifié par')),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'activation/désactivation", null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Configuration Prospection',
                'verbose_name_plural': 'Configuration Prospection',
            },
        ),
    ]
