# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospection', '0001_initial'),
        ('academic', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='etablissement_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name="Établissement d'origine"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='agents',
            field=models.ManyToManyField(related_name='equipes', to='prospection.agent', verbose_name='Agents'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='chef_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_dirigees', to='prospection.agent', verbose_name="Chef d'équipe"),
        ),
        migrations.AddField(
            model_name='equipe',
            name='etablissement_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Établissement cible'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='prospection.seanceprospection', verbose_name='Séance'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear', verbose_name='Année académique'),
        ),
        migrations.AlterUniqueTogether(
            name='seanceprospection',
            unique_together={('campagne', 'date_seance')},
        ),
        migrations.AlterUniqueTogether(
            name='prospect',
            unique_together={('telephone', 'equipe')},
        ),
    ]
