# Generated by Django 5.2.1 on 2025-07-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospection', '0002_prospectionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom de l'équipe"),
        ),
    ]
