# Generated by Django 4.2.28 on 2026-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Si activée, un code de vérification est envoyé par email à chaque connexion.', verbose_name='Double authentification activée'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='two_factor_user_can_manage',
            field=models.BooleanField(default=True, help_text="Si décoché, l'utilisateur ne peut pas activer ou désactiver lui-même la double authentification depuis son profil.", verbose_name="L'utilisateur peut gérer sa double authentification"),
        ),
    ]
