# Generated by Django 5.2.1 on 2025-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='method_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
