# Generated by Django 4.2.28 on 2026-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessModule',
            fields=[
                ('code', models.CharField(choices=[('scholar', 'Scolarité'), ('teaching', 'Suivi des enseignements'), ('planning', 'Planification'), ('prospection', 'Prospection'), ('payments', 'Paiements')], max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Module d'accès",
                'verbose_name_plural': "Modules d'accès",
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_accessed_module',
            field=models.CharField(blank=True, choices=[('scholar', 'Scolarité'), ('teaching', 'Suivi des enseignements'), ('planning', 'Planification'), ('prospection', 'Prospection'), ('payments', 'Paiements')], max_length=50, null=True, verbose_name='Dernier module accédé'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='accessible_modules',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.accessmodule', verbose_name='Modules accessibles'),
        ),
    ]
