# Generated by Django 5.2.1 on 2025-05-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_gender_baseuser_method_type_baseuser_role'),
        ('students', '0002_studentmetadata_remove_student_method_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMetaData',
        ),
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
