# Generated by Django 5.2.1 on 2025-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_studentmetadata_alter_baseuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scholar", "Scolarité"),
                    ("study", "Suivie des Enseignement"),
                    ("student", "Étudiant"),
                    ("super_admin", "Administrateur"),
                ],
                default="student",
                max_length=100,
                null=True,
            ),
        ),
    ]
