# Generated by Django 4.2.28 on 2026-05-25 14:15

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_access_modules'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
                ('objects', accounts.models.BaseUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='role',
        ),
    ]
