# Generated by Django 5.2.1 on 2025-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_baseuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, choices=[('scholar', 'Scolarité'), ('teaching', 'Suivie des Enseignements'), ('student', 'Étudiant'), ('super_admin', 'Administrateur')], default='student', max_length=100, null=True),
        ),
    ]
