# Generated by Django 5.2.1 on 2025-06-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_baseuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='method_type',
        ),
    ]
