# Generated by Django 5.2.1 on 2025-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_baseuser_method_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='godfather',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout"),
        ),
        migrations.AddField(
            model_name='godfather',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
    ]
