# Generated by Django 4.2.28 on 2026-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_recruitment_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodule',
            name='code',
            field=models.CharField(choices=[('scholar', 'Scolarité'), ('teaching', 'Suivi des enseignements'), ('planning', 'Planification'), ('prospection', 'Prospection'), ('payments', 'Paiements'), ('lecturer_management', 'Gestion des enseignants')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_accessed_module',
            field=models.CharField(blank=True, choices=[('scholar', 'Scolarité'), ('teaching', 'Suivi des enseignements'), ('planning', 'Planification'), ('prospection', 'Prospection'), ('payments', 'Paiements'), ('lecturer_management', 'Gestion des enseignants')], max_length=50, null=True, verbose_name='Dernier module accédé'),
        ),
    ]
