# Generated by Django 5.2.1 on 2025-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_godfather_created_at_godfather_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="godfather",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="godfather",
            name="lastname",
        ),
        migrations.RemoveField(
            model_name="godfather",
            name="user",
        ),
        migrations.AddField(
            model_name="godfather",
            name="full_name",
            field=models.CharField(default="Ramiro", max_length=200),
            preserve_default=False,
        ),
    ]
