# Generated by Django 5.2.1 on 2025-07-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_godfather_firstname_remove_godfather_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, choices=[('scholar', 'Scolarité'), ('planning', 'Planification'), ('teaching', 'Suivie des Enseignements'), ('student', 'Étudiant'), ('super_admin', 'Administrateur')], default='student', max_length=100, null=True),
        ),
    ]
