# Generated by Django 4.2.28 on 2026-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accessmodule_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Photo de profil'),
        ),
    ]
