# Generated by Django 5.2.1 on 2025-05-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_at", models.DateField()),
                ("end_at", models.DateField()),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Année Académique",
                "verbose_name_plural": "Années Académiques",
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("credit_count", models.IntegerField()),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="academic.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=200)),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="academic.speciality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
            },
        ),
    ]
