# Generated by Django 4.2.28 on 2026-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='minimum_diploma',
            field=models.CharField(blank=True, choices=[('BTS', 'BTS'), ('HND', 'HND'), ('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], help_text="Le diplôme minimum requis pour accéder à ce niveau. Laisser vide si aucun diplôme n'est requis.", max_length=20, null=True, verbose_name='Diplôme minimum requis pour enseigner à ce niveau'),
        ),
    ]
