# Generated by Django 5.2.1 on 2025-06-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_level_method_type_alter_level_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='department',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='method_type',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
