# Generated by Django 5.2.1 on 2025-06-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_academicyear_method_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
