# Generated by Django 4.2.28 on 2026-05-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_subject_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code du cours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_count',
            field=models.IntegerField(verbose_name='Nombre de crédits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Intitulé du cours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.program', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.speciality', verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.subject', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='level',
            name='minimum_diploma',
            field=models.CharField(blank=True, choices=[('BTS', 'BTS'), ('HND', 'HND'), ('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], help_text="Le diplôme minimum requis pour un enseignant pour enseigner à ce niveau. Laisser vide si aucun diplôme n'est requis.", max_length=20, null=True, verbose_name='Diplôme minimum requis pour enseigner à ce niveau'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom de la matière'),
        ),
    ]
