# Generated by Django 5.2.1 on 2025-06-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_academicyear_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Année Académique Active'),
        ),
    ]
