# Generated by Django 4.2.28 on 2026-05-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_course_course_code_alter_course_credit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='cycle',
            field=models.CharField(blank=True, choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], default='Licence', max_length=20, verbose_name='Cycle'),
        ),
    ]
