# Generated by Django 4.2.28 on 2026-05-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_level_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='Laisser vide pour générer automatiquement un code à partir de la matière/intitulé et du niveau.', max_length=20, primary_key=True, serialize=False, verbose_name='Code du cours'),
        ),
    ]
