# Generated by Django 4.2.28 on 2026-06-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeachingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('courses', models.ManyToManyField(blank=True, related_name='teaching_units', to='academic.course', verbose_name='Cours associés')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_unit_specialities', to='academic.program')),
            ],
            options={
                'verbose_name': "Unité d'enseignement",
                'verbose_name_plural': "Unités d'enseignement",
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_courses', to='academic.teachingunit', verbose_name="Unité d'enseignement"),
        ),
    ]
