# Generated by Django 5.2.1 on 2025-06-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_academicyear_created_at_academicyear_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='label',
            new_name='name',
        ),
    ]
