# Generated by Django 4.2.28 on 2026-06-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_speciality_description_teachingunit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Domaine', 'verbose_name_plural': 'Domaines'},
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academic.subject', verbose_name='Domaine'),
        ),
    ]
