# Generated by Django 5.2.1 on 2025-07-14 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_department_speciality_course_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialities', to='academic.program'),
        ),
    ]
