# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='YSEM', max_length=200, verbose_name="Nom de l'institution")),
                ('institution_long_name', models.CharField(default='Yaoundé Higher School of Economic and Management', max_length=200, verbose_name="Nom complet de l'institution")),
                ('institution_code', models.CharField(default='YSEM001', max_length=50, verbose_name="Code de l'institution")),
                ('address', models.TextField(default='Damas, Yaoundé, Cameroun', verbose_name='Adresse')),
                ('phone', models.CharField(default='+237 XXX XXX XXX', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(default='contact@ysem.education', max_length=254, verbose_name='Email')),
                ('website', models.URLField(default='https://www.ysem.education', verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/logo/', verbose_name="Logo de l'institution")),
                ('timezone', models.CharField(default='Africa/Douala', max_length=50, verbose_name='Fuseau horaire')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('inscription_period', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('limited', 'Limitée')], default='open', max_length=20, verbose_name="Période d'inscription")),
                ('auto_approval', models.BooleanField(default=True, verbose_name='Approbation automatique')),
                ('require_documents', models.BooleanField(default=True, verbose_name='Exiger les documents')),
                ('allow_external_registration', models.BooleanField(default=True, verbose_name="Autoriser l'inscription externe")),
                ('auto_level_progression', models.BooleanField(default=True, verbose_name='Progression automatique de niveau')),
                ('allow_level_change', models.BooleanField(default=False, verbose_name='Autoriser le changement de niveau')),
                ('require_level_validation', models.BooleanField(default=True, verbose_name='Exiger la validation de niveau')),
                ('allow_program_change', models.BooleanField(default=False, verbose_name='Autoriser le changement de programme')),
                ('require_program_validation', models.BooleanField(default=True, verbose_name='Exiger la validation de programme')),
                ('default_role', models.CharField(default='student', max_length=20, verbose_name='Rôle par défaut')),
                ('session_timeout', models.IntegerField(default=30, verbose_name="Délai d'expiration de session (minutes)")),
                ('view_documents', models.BooleanField(default=True, verbose_name='Voir les documents')),
                ('download_docs', models.BooleanField(default=True, verbose_name='Télécharger les documents')),
                ('update_profile', models.BooleanField(default=True, verbose_name='Mettre à jour le profil')),
                ('view_statistics', models.BooleanField(default=False, verbose_name='Voir les statistiques')),
                ('max_file_size', models.IntegerField(default=5, verbose_name='Taille maximale de fichier (MB)')),
                ('allowed_formats', models.CharField(default='PNG, JPG, PDF', max_length=100, verbose_name='Formats autorisés')),
                ('student_card_enabled', models.BooleanField(default=True, verbose_name="Carte d'étudiant activée")),
                ('transcript_enabled', models.BooleanField(default=True, verbose_name='Relevé de notes activé')),
                ('certificate_enabled', models.BooleanField(default=True, verbose_name='Certificat activé')),
                ('diploma_enabled', models.BooleanField(default=True, verbose_name='Diplôme activé')),
                ('require_original_docs', models.BooleanField(default=True, verbose_name='Exiger les documents originaux')),
                ('email_enrollment', models.BooleanField(default=True, verbose_name="Email d'inscription")),
                ('email_documents', models.BooleanField(default=True, verbose_name='Email de documents')),
                ('email_deadlines', models.BooleanField(default=False, verbose_name="Email d'échéances")),
                ('system_errors', models.BooleanField(default=True, verbose_name='Erreurs système')),
                ('system_updates', models.BooleanField(default=False, verbose_name='Mises à jour système')),
                ('backup_frequency', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=20, verbose_name='Fréquence de sauvegarde')),
                ('data_retention', models.IntegerField(default=7, verbose_name='Rétention des données (années)')),
                ('audit_log', models.BooleanField(default=True, verbose_name="Journal d'audit")),
                ('data_encryption', models.BooleanField(default=True, verbose_name='Chiffrement des données')),
                ('auto_cleanup', models.BooleanField(default=False, verbose_name='Nettoyage automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Paramètres Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
    ]
