# Generated by Django 5.2.1 on 2025-07-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='YSEM - École Supérieure', max_length=200)),
                ('institution_code', models.CharField(default='YSEM001', max_length=50)),
                ('address', models.TextField(default="123 Avenue de l'Université, Douala, Cameroun")),
                ('phone', models.CharField(default='+237 XXX XXX XXX', max_length=20)),
                ('email', models.EmailField(default='contact@ysem.edu.cm', max_length=254)),
                ('website', models.URLField(default='https://www.ysem.edu.cm')),
                ('timezone', models.CharField(default='Africa/Douala', max_length=50)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('inscription_period', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('limited', 'Limitée')], default='open', max_length=20)),
                ('auto_approval', models.BooleanField(default=True)),
                ('require_documents', models.BooleanField(default=True)),
                ('allow_external_registration', models.BooleanField(default=True)),
                ('auto_level_progression', models.BooleanField(default=True)),
                ('allow_level_change', models.BooleanField(default=False)),
                ('require_level_validation', models.BooleanField(default=True)),
                ('allow_program_change', models.BooleanField(default=False)),
                ('require_program_validation', models.BooleanField(default=True)),
                ('default_role', models.CharField(default='student', max_length=20)),
                ('session_timeout', models.IntegerField(default=30)),
                ('view_documents', models.BooleanField(default=True)),
                ('download_docs', models.BooleanField(default=True)),
                ('update_profile', models.BooleanField(default=True)),
                ('view_statistics', models.BooleanField(default=False)),
                ('max_file_size', models.IntegerField(default=5)),
                ('allowed_formats', models.CharField(default='PNG, JPG, PDF', max_length=100)),
                ('student_card_enabled', models.BooleanField(default=True)),
                ('transcript_enabled', models.BooleanField(default=True)),
                ('certificate_enabled', models.BooleanField(default=True)),
                ('diploma_enabled', models.BooleanField(default=True)),
                ('require_original_docs', models.BooleanField(default=True)),
                ('email_enrollment', models.BooleanField(default=True)),
                ('email_documents', models.BooleanField(default=True)),
                ('email_deadlines', models.BooleanField(default=False)),
                ('system_errors', models.BooleanField(default=True)),
                ('system_updates', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=20)),
                ('data_retention', models.IntegerField(default=7)),
                ('audit_log', models.BooleanField(default=True)),
                ('data_encryption', models.BooleanField(default=True)),
                ('auto_cleanup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
    ]
