# Generated by Django 4.2.28 on 2026-05-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='require_experience_for_doctors_to_teach_doctors',
            field=models.BooleanField(default=True, verbose_name="Nombre d'années d'expérience requis pour les enseignants ayant un Doctorat à enseigner en Doctorat"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_experience_for_licence_to_teach_licence',
            field=models.BooleanField(default=True, verbose_name="Nombre d'années d'expérience requis pour les enseignants ayant une Licence à enseigner en Licence"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_experience_for_masters_to_teach_masters',
            field=models.BooleanField(default=True, verbose_name="Nombre d'années d'expérience requis pour les enseignants ayant un Master à enseigner en Master"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='teacher_recruitment_open',
            field=models.BooleanField(default=True, verbose_name='Recrutement des enseignants ouvert'),
        ),
    ]
