# Generated by Django 5.2.1 on 2025-07-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='address',
            field=models.TextField(default='Damas, Yaoundé, Cameroun'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email',
            field=models.EmailField(default='contact@ysem.education', max_length=254),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='website',
            field=models.URLField(default='https://www.ysem.education'),
        ),
    ]
