# Generated by Django 4.2.28 on 2026-05-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_systemsettings_require_experience_for_doctors_to_teach_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='require_experience_for_doctors_to_teach_doctors',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'années d'expérience requis pour les enseignants ayant un Doctorat à enseigner en Doctorat"),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='require_experience_for_licence_to_teach_licence',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'années d'expérience requis pour les enseignants ayant une Licence à enseigner en Licence"),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='require_experience_for_masters_to_teach_masters',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'années d'expérience requis pour les enseignants ayant un Master à enseigner en Master"),
        ),
    ]
