# Generated by Django 4.2.28 on 2026-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_systemsettings_allow_level_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='phone',
            field=models.CharField(default='+237 XXX XXX XXX', max_length=40, verbose_name='Téléphone'),
        ),
    ]
