# Generated by Django 4.2.28 on 2026-05-11 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'Utilisateur'), ('student', 'Étudiant'), ('agent', 'Agent'), ('anonymous', 'Anonyme')], default='anonymous', max_length=20)),
                ('actor_id', models.PositiveIntegerField(blank=True, help_text="Identifiant interne lorsque l'acteur n'est pas un BaseUser (étudiant, agent...).", null=True)),
                ('actor_identifier', models.CharField(blank=True, max_length=255)),
                ('actor_display', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(choices=[('web', 'Application web'), ('student_portal', 'Portail étudiant'), ('api', 'API / Mobile')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Connexion réussie'), ('failed', 'Échec de connexion'), ('logged_out', 'Déconnexion')], default='success', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_family', models.CharField(blank=True, max_length=100)),
                ('browser_family', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_family', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('device_label', models.CharField(blank=True, max_length=255)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_raw', models.JSONField(blank=True, default=dict)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('is_known_device', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-login_at', '-id'],
                'indexes': [models.Index(fields=['actor_type', 'actor_id'], name='authenticat_actor_t_bd83d5_idx'), models.Index(fields=['user', 'device_fingerprint'], name='authenticat_user_id_8a189b_idx'), models.Index(fields=['status', 'login_at'], name='authenticat_status_d6054a_idx')],
            },
        ),
    ]
