# Generated by Django 4.2.28 on 2026-05-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Connexion'), ('toggle_2fa', 'Modification du statut 2FA')], default='login', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('requested_state', models.BooleanField(blank=True, help_text="Pour un défi 'toggle_2fa', valeur cible de two_factor_enabled après validation.", null=True)),
                ('next_url', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi de double authentification',
                'verbose_name_plural': 'Défis de double authentification',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'purpose', 'consumed_at'], name='authenticat_user_id_83da1a_idx')],
            },
        ),
    ]
