# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('model', 'Modèle'), ('auth', 'Authentification'), ('business', 'Métier'), ('m2m', 'Relation M2M')], max_length=20)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('m2m_add', 'Ajout M2M'), ('m2m_remove', 'Suppression M2M'), ('m2m_clear', 'Vidage M2M'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Échec de connexion'), ('password_change', 'Changement de mot de passe'), ('bulk_update', 'Mise à jour en masse'), ('bulk_delete', 'Suppression en masse')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('actor_type', models.CharField(blank=True, max_length=30)),
                ('actor_agent_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor_identifier', models.CharField(blank=True, max_length=255)),
                ('actor_display', models.CharField(blank=True, max_length=255)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('target_app_label', models.CharField(blank=True, max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "Entrée de journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['category', 'action'], name='audit_audit_categor_cbd840_idx'), models.Index(fields=['target_app_label', 'target_model', 'target_object_id'], name='audit_audit_target__1d2aac_idx')],
            },
        ),
    ]
