# Generated by Django 4.2.28 on 2026-04-22 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teaching', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('code', models.CharField(default='TEMP', max_length=20, primary_key=True, serialize=False, verbose_name='Code du batiment')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du batiment')),
            ],
            options={
                'verbose_name': 'Batiment',
                'verbose_name_plural': 'Batiments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code de la salle')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bâtiment')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Étage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Salle active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Date de suppression')),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code équipement')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'équipement")),
            ],
            options={
                'verbose_name': 'Equipement',
                'verbose_name_plural': 'Equipements',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numéro étage')),
                ('name', models.CharField(max_length=100, verbose_name="Nom d'étage")),
            ],
            options={
                'verbose_name': 'Etage',
                'verbose_name_plural': 'Etages',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'emploi du temps")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('duration_type', models.CharField(choices=[('1_month', '1 mois'), ('3_months', '3 mois'), ('6_months', '6 mois'), ('1_year', '1 année'), ('custom', 'Personnalisé')], default='3_months', max_length=20, verbose_name='Type de durée')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Généré automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.academicyear', verbose_name='Année académique')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.level', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'academic_year', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Créneau actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('lecture', 'Cours magistral'), ('tutorial', 'Travaux dirigés'), ('practical', 'Travaux pratiques'), ('exam', 'Examen'), ('other', 'Autre')], default='lecture', max_length=20, verbose_name='Type de séance')),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('postponed', 'Reportée')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('date', models.DateField(verbose_name='Date de la séance')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(8.0)], verbose_name='Durée (heures)')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sujet/Chapitre')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('attendance_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de présents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.academicyear', verbose_name='Année académique')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planification.classroom', verbose_name='Salle de classe')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.course', verbose_name='Cours')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Teaching.lecturer', verbose_name='Enseignant')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.level', verbose_name='Niveau')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planification.timeslot', verbose_name='Créneau horaire')),
            ],
            options={
                'verbose_name': 'Séance de cours',
                'verbose_name_plural': 'Séances de cours',
                'ordering': ['-date', 'time_slot__start_time'],
                'unique_together': {('classroom', 'time_slot', 'date')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='planification.equipment', verbose_name='Équipements disponibles'),
        ),
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Numéro de semaine')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Séance récurrente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sessions', to='planification.coursesession', verbose_name='Séance de cours')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sessions', to='planification.schedule', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': "Séance d'emploi du temps",
                'verbose_name_plural': "Séances d'emploi du temps",
                'ordering': ['week_number', 'course_session__time_slot__start_time'],
                'unique_together': {('schedule', 'course_session')},
            },
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible'), ('preferred', 'Préféré')], default='available', max_length=20, verbose_name='Statut de disponibilité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début (optionnel)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin (optionnel)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_availabilities', to='academic.academicyear', verbose_name='Année académique')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Teaching.lecturer', verbose_name='Enseignant')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_availabilities', to='planification.timeslot', verbose_name='Créneau horaire')),
            ],
            options={
                'verbose_name': 'Disponibilité enseignant',
                'verbose_name_plural': 'Disponibilités enseignants',
                'ordering': ['lecturer__lastname', 'time_slot__start_time'],
                'unique_together': {('lecturer', 'time_slot', 'academic_year', 'start_date', 'end_date')},
            },
        ),
    ]
