# Generated by Django 5.2.1 on 2025-07-13 21:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teaching', '0001_initial'),
        ('academic', '0007_rename_label_program_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code de la salle')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bâtiment')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Étage')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='Équipements disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Salle active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du créneau')),
                ('day_of_week', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Créneau actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('lecture', 'Cours magistral'), ('tutorial', 'Travaux dirigés'), ('practical', 'Travaux pratiques'), ('exam', 'Examen'), ('other', 'Autre')], default='lecture', max_length=20, verbose_name='Type de séance')),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('postponed', 'Reportée')], default='scheduled', max_length=20, verbose_name='Statut')),
                ('date', models.DateField(verbose_name='Date de la séance')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(8.0)], verbose_name='Durée (heures)')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sujet/Chapitre')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('attendance_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de présents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.academicyear', verbose_name='Année académique')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planification.classroom', verbose_name='Salle de classe')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.course', verbose_name='Cours')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Teaching.lecturer', verbose_name='Enseignant')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.level', verbose_name='Niveau')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='planification.timeslot', verbose_name='Créneau horaire')),
            ],
            options={
                'verbose_name': 'Séance de cours',
                'verbose_name_plural': 'Séances de cours',
                'ordering': ['-date', 'time_slot__start_time'],
                'unique_together': {('classroom', 'time_slot', 'date')},
            },
        ),
    ]
