# Generated by Django 5.2.1 on 2025-07-13 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teaching', '0001_initial'),
        ('academic', '0007_rename_label_program_name'),
        ('planification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'emploi du temps")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('duration_type', models.CharField(choices=[('1_month', '1 mois'), ('3_months', '3 mois'), ('6_months', '6 mois'), ('1_year', '1 année'), ('custom', 'Personnalisé')], default='3_months', max_length=20, verbose_name='Type de durée')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Généré automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.academicyear', verbose_name='Année académique')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.level', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'academic_year', 'level')},
            },
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible'), ('preferred', 'Préféré')], default='available', max_length=20, verbose_name='Statut de disponibilité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début (optionnel)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin (optionnel)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_availabilities', to='academic.academicyear', verbose_name='Année académique')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Teaching.lecturer', verbose_name='Enseignant')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_availabilities', to='planification.timeslot', verbose_name='Créneau horaire')),
            ],
            options={
                'verbose_name': 'Disponibilité enseignant',
                'verbose_name_plural': 'Disponibilités enseignants',
                'ordering': ['lecturer__lastname', 'time_slot__day_of_week', 'time_slot__start_time'],
                'unique_together': {('lecturer', 'time_slot', 'academic_year', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Numéro de semaine')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Séance récurrente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sessions', to='planification.coursesession', verbose_name='Séance de cours')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sessions', to='planification.schedule', verbose_name='Emploi du temps')),
            ],
            options={
                'verbose_name': "Séance d'emploi du temps",
                'verbose_name_plural': "Séances d'emploi du temps",
                'ordering': ['week_number', 'course_session__time_slot__day_of_week', 'course_session__time_slot__start_time'],
                'unique_together': {('schedule', 'course_session')},
            },
        ),
    ]
