# Generated by Django 4.2.28 on 2026-05-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_remove_lecturer_favorite_subjects_lecturer_cv_and_more'),
        ('planification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lecturers.lecturer', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='lectureravailability',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='lecturers.lecturer', verbose_name='Enseignant'),
        ),
    ]
