# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('matricule', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Matricule')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de famille')),
                ('date_naiss', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade/Titre')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True, verbose_name='Genre')),
                ('lang', models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalité')),
                ('number_of_dependent_children', models.IntegerField(blank=True, null=True, verbose_name="Nombre d'enfants à charge")),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=20, null=True, verbose_name='Statut marital')),
                ('has_health_problem', models.BooleanField(default=False, verbose_name='Avez-vous des problèmes de santé?')),
                ('health_problem_description', models.TextField(blank=True, null=True, verbose_name='Description des problèmes de santé')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse de résidence')),
                ('nic', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de CNI')),
                ('niu', models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro d'Identification Unique")),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'urgence - Nom")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Contact d'urgence - Téléphone")),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Contact d'urgence - Email")),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name="Contact d'urgence - Relation")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lecturers/photos/', verbose_name='Photo de profil')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='lecturers/signatures/', verbose_name='Signature')),
                ('highest_diploma_obtained', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dernier diplôme obtenu')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='TeachingMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('cycle', models.CharField(blank=True, max_length=200, verbose_name='Projet fin de cours')),
                ('totalChapterCount', models.IntegerField(verbose_name='Chapitres prévus')),
                ('chapitre_fait', models.IntegerField(verbose_name='Chapitres faits')),
                ('contenu_seance_prevu', models.IntegerField(verbose_name='Contenu séance prévu dans le plan')),
                ('contenu_effectif_seance', models.IntegerField(verbose_name='Contenu effectif séance dans le cahier de texte')),
                ('travaux_preparatoires', models.BooleanField(default=True, verbose_name='Travaux préparatoires')),
                ('groupWork', models.BooleanField(default=True, verbose_name='Travaux en équipe')),
                ('classWork', models.BooleanField(default=True, verbose_name='Travaux en salle')),
                ('homeWork', models.BooleanField(default=True, verbose_name='Travaux maison')),
                ('pedagogicActivities', models.BooleanField(default=True, verbose_name='Activités pédagogiques')),
                ('TDandTP', models.BooleanField(default=True, verbose_name='TD et TP')),
                ('projet_fin_cours', models.CharField(blank=True, max_length=200, verbose_name='Projet fin de cours')),
                ('association_pratique_aux_enseigements', models.CharField(blank=True, max_length=200, verbose_name='Association pratique aux enseignements')),
                ('observation', models.CharField(blank=True, max_length=200, verbose_name='Observation')),
                ('solution', models.CharField(blank=True, max_length=200, verbose_name='Résolution')),
                ('generalObservation', models.CharField(blank=True, max_length=200, verbose_name='Observation générale')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.academicyear', verbose_name='Année académique')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.course', verbose_name='Cours')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='Teaching.lecturer', verbose_name='Enseignant')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.level', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Suivi de cours',
                'verbose_name_plural': 'Suivi des cours',
                'ordering': ['-date', 'lecturer__lastname', 'lecturer__firstname'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluationDat', models.DateField(null=True, verbose_name="Date d'évaluation")),
                ('support_cours_acessible', models.BooleanField(default=True, verbose_name='Support de cours accessible')),
                ('bonne_explication_cours', models.BooleanField(default=True, verbose_name='Bonne explication du cours')),
                ('bonne_reponse_questions', models.BooleanField(default=True, verbose_name='Bonne réponse aux questions')),
                ('courseMethodology', models.CharField(blank=True, default='', max_length=200, verbose_name='Méthodologie du cours')),
                ('donne_TD', models.BooleanField(default=True, verbose_name='Donne des TD')),
                ('donne_projet', models.BooleanField(default=True, verbose_name='Donne des projets')),
                ('difficulte_rencontree', models.BooleanField(default=False, verbose_name='Difficultés rencontrées')),
                ('quelles_difficultes_rencontrees', models.TextField(blank=True, verbose_name='Quelles difficultés rencontrées')),
                ('propositionEtudiants', models.TextField(blank=True, verbose_name='Propositions des étudiants')),
                ('observationSSAC', models.TextField(blank=True, verbose_name='Observation SSAC')),
                ('actionSSAC', models.TextField(verbose_name='Action SSAC')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.academicyear', verbose_name='Année académique')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.course', verbose_name='Cours')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.level', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-evaluationDat', 'student__lastname', 'student__firstname'],
            },
        ),
    ]
