# Generated by Django 5.2.1 on 2025-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseSupportAvailable', models.BooleanField(default=True)),
                ('goodExplanation', models.BooleanField(default=True)),
                ('goodQuestionAnswer', models.BooleanField(default=True)),
                ('courseMethodology', models.CharField(max_length=200)),
                ('giveWork', models.BooleanField(default=True)),
                ('difficulty', models.BooleanField(default=True)),
                ('anyDifficulty', models.BooleanField(default=True)),
                ('difficulties', models.CharField(max_length=200)),
                ('ssacAction', models.CharField(max_length=200)),
                ('ssacObservation', models.CharField(max_length=200)),
                ('studentProposition', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_naiss', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('lang', models.CharField(default='fr', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Enseignants',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='TeachingMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalChapterCount', models.IntegerField()),
                ('groupWork', models.BooleanField(default=True)),
                ('classWork', models.BooleanField(default=True)),
                ('homeWork', models.BooleanField(default=True)),
                ('pedagogicActivities', models.BooleanField(default=True)),
                ('TDandTP', models.BooleanField(default=True)),
                ('TDandTPContent', models.CharField(max_length=200)),
                ('observation', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=200)),
                ('generalObservation', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Suivi_Cours',
                'verbose_name_plural': 'Suivi_Cours',
            },
        ),
    ]
