# Generated by Django 5.2.1 on 2025-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluationDat", models.DateField(null=True, verbose_name="date")),
                ("nom_et_prenom_etudiant", models.CharField(max_length=200)),
                ("cycle", models.CharField(max_length=200)),
                ("niveau", models.IntegerField(default="")),
                ("intitule_cours", models.CharField(max_length=200)),
                ("support_cours_acessible", models.BooleanField(default=True)),
                ("bonne_explication_cours", models.BooleanField(default=True)),
                ("bonne_reponse_questions", models.BooleanField(default=True)),
                (
                    "courseMethodology",
                    models.CharField(
                        default="", max_length=200, verbose_name="methodologie_cours"
                    ),
                ),
                ("donne_TD", models.BooleanField(default=True)),
                ("donne_projet", models.BooleanField(default=True)),
                ("difficulte_rencontree", models.BooleanField(default=True)),
                (
                    "quelles_difficultes_rencontrees",
                    models.CharField(default="", max_length=200),
                ),
                ("propositionEtudiants", models.CharField(default="", max_length=200)),
                ("observationSSAC", models.CharField(default="", max_length=200)),
                ("actionSSAC", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Evaluation",
                "verbose_name_plural": "Evaluations",
            },
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "matricule",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("date_naiss", models.DateField()),
                ("grade", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=10
                    ),
                ),
                ("lang", models.CharField(default="fr", max_length=50)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Enseignants",
                "verbose_name_plural": "Enseignants",
            },
        ),
        migrations.CreateModel(
            name="TeachingMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                ("intitule_cours", models.CharField(max_length=200)),
                ("cycle", models.CharField(max_length=200)),
                ("niveau", models.IntegerField()),
                (
                    "totalChapterCount",
                    models.IntegerField(verbose_name="chapitre prevu"),
                ),
                ("chapitre_fait", models.IntegerField()),
                ("contenu_seance_prevu", models.IntegerField()),
                ("contenu_effectif_seance", models.IntegerField()),
                ("travaux_preparatoires", models.BooleanField(default=True)),
                (
                    "groupWork",
                    models.BooleanField(default=True, verbose_name="travaux_equipe"),
                ),
                (
                    "classWork",
                    models.BooleanField(default=True, verbose_name="travaux_salle"),
                ),
                (
                    "homeWork",
                    models.BooleanField(default=True, verbose_name="travaux_maison"),
                ),
                (
                    "pedagogicActivities",
                    models.BooleanField(
                        default=True, verbose_name="activite_pedagogique"
                    ),
                ),
                ("TDandTP", models.BooleanField(default=True, verbose_name="TD et TP")),
                ("projet_fin_cours", models.CharField(max_length=200)),
                (
                    "association_pratique_aux_enseigements",
                    models.CharField(max_length=200),
                ),
                ("observation", models.CharField(max_length=200)),
                (
                    "solution",
                    models.CharField(max_length=200, verbose_name="resolution"),
                ),
                (
                    "generalObservation",
                    models.CharField(
                        max_length=200, verbose_name="observation generale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi_Cours",
                "verbose_name_plural": "Suivi_Cours",
            },
        ),
    ]
