# Generated by Django 5.2.1 on 2025-06-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingmonitoring',
            name='taux_couverture_seance',
        ),
    ]
