# Generated by Django 5.2.1 on 2025-07-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingmonitoring',
            options={'verbose_name': 'Suivie de cours', 'verbose_name_plural': 'Suivie des cours'},
        ),
    ]
