# Generated by Django 5.2.1 on 2025-06-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teaching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='status',
            new_name='grade',
        ),
    ]
