# Generated by Django 4.2.28 on 2026-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_course_course_code_alter_course_credit_count_and_more'),
        ('Teaching', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, related_name='favorite_lecturers', to='academic.course', verbose_name='Matières préférées'),
        ),
    ]
