# Generated by Django 4.2.28 on 2026-05-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0002_alter_coursesession_lecturer_and_more'),
        ('lecturers', '0002_remove_lecturer_favorite_subjects_lecturer_cv_and_more'),
        ('Teaching', '0003_lecturer_favorite_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='lecturers.lecturer', verbose_name='Enseignant'),
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
