# Generated by Django 5.2.1 on 2025-07-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teaching', '0003_alter_evaluation_options_remove_evaluation_cycle_and_more'),
        ('academic', '0009_speciality_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingmonitoring',
            options={'ordering': ['-date', 'lecturer__lastname', 'lecturer__firstname'], 'verbose_name': 'Suivi de cours', 'verbose_name_plural': 'Suivi des cours'},
        ),
        migrations.AddField(
            model_name='teachingmonitoring',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.academicyear', verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='teachingmonitoring',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.course', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='teachingmonitoring',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='Teaching.lecturer', verbose_name='Enseignant'),
        ),
        migrations.AddField(
            model_name='teachingmonitoring',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.level', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='association_pratique_aux_enseigements',
            field=models.CharField(blank=True, max_length=200, verbose_name='Association pratique aux enseignements'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='chapitre_fait',
            field=models.IntegerField(verbose_name='Chapitres faits'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='classWork',
            field=models.BooleanField(default=True, verbose_name='Travaux en salle'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='contenu_effectif_seance',
            field=models.IntegerField(verbose_name='Contenu effectif séance'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='contenu_seance_prevu',
            field=models.IntegerField(verbose_name='Contenu séance prévu'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='cycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='generalObservation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observation générale'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='groupWork',
            field=models.BooleanField(default=True, verbose_name='Travaux en équipe'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='homeWork',
            field=models.BooleanField(default=True, verbose_name='Travaux maison'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='intitule_cours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='niveau',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='observation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='pedagogicActivities',
            field=models.BooleanField(default=True, verbose_name='Activités pédagogiques'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='projet_fin_cours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Projet fin de cours'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='solution',
            field=models.CharField(blank=True, max_length=200, verbose_name='Résolution'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='totalChapterCount',
            field=models.IntegerField(verbose_name='Chapitres prévus'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='travaux_preparatoires',
            field=models.BooleanField(default=True, verbose_name='Travaux préparatoires'),
        ),
    ]
