# Generated by Django 5.2.1 on 2025-07-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teaching', '0005_data_migration'),
        ('academic', '0009_speciality_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingmonitoring',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='teachingmonitoring',
            name='intitule_cours',
        ),
        migrations.RemoveField(
            model_name='teachingmonitoring',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='teachingmonitoring',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='teachingmonitoring',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.academicyear', verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='Teaching.lecturer', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='teachingmonitoring',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_monitorings', to='academic.level', verbose_name='Niveau'),
        ),
    ]
