# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('higher', 'Supérieur')], max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
            },
        ),
        migrations.CreateModel(
            name='SecondaryDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('name', models.CharField(max_length=200)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('obtained_year', models.IntegerField()),
                ('mention', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Diplôme Secondaire',
                'verbose_name_plural': 'Diplômes Secondaires',
            },
        ),
        migrations.CreateModel(
            name='UniversityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('level_name', models.CharField(max_length=100)),
                ('diploma_name', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Niveau Universitaire',
                'verbose_name_plural': 'Niveaux Universitaires',
            },
        ),
    ]
