# Generated by Django 5.2.1 on 2025-05-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("level", models.CharField(max_length=100)),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "École",
                "verbose_name_plural": "Écoles",
            },
        ),
        migrations.CreateModel(
            name="SecondaryDiploma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("serie", models.CharField(blank=True, max_length=100, null=True)),
                ("obtained_year", models.IntegerField()),
                ("mention", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Diplôme Secondaire",
                "verbose_name_plural": "Diplômes Secondaires",
            },
        ),
        migrations.CreateModel(
            name="UniversityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_name", models.CharField(max_length=100)),
                (
                    "diploma_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("speciality", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "academic_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "method_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Niveau Universitaire",
                "verbose_name_plural": "Niveaux Universitaires",
            },
        ),
    ]
