# Generated by Django 5.2.1 on 2025-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='secondarydiploma',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='universitylevel',
            name='method_type',
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout"),
        ),
        migrations.AddField(
            model_name='school',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='secondarydiploma',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout"),
        ),
        migrations.AddField(
            model_name='secondarydiploma',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='universitylevel',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name="Date d'ajout"),
        ),
        migrations.AddField(
            model_name='universitylevel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
    ]
