# Generated by Django 4.2.28 on 2026-04-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitylevel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_levels', to='students.student', verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='universitylevel',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_levels', to='schools.school', verbose_name='Université fréquentée'),
        ),
        migrations.AddField(
            model_name='secondarydiploma',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_diplomas', to='schools.school', verbose_name="École d'obtention"),
        ),
        migrations.AddField(
            model_name='secondarydiploma',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_diplomas', to='students.student', verbose_name='Étudiant'),
        ),
    ]
