# Generated by Django 5.2.1 on 2025-07-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_school_method_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('higher', 'Supérieur')], max_length=100),
        ),
    ]
