# Generated by Django 4.2.28 on 2026-05-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_alter_course_course_code_alter_course_credit_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('matricule', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Matricule')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de famille')),
                ('date_naiss', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade/Titre')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True, verbose_name='Genre')),
                ('lang', models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalité')),
                ('number_of_dependent_children', models.IntegerField(blank=True, null=True, verbose_name="Nombre d'enfants à charge")),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=20, null=True, verbose_name='Statut marital')),
                ('has_health_problem', models.BooleanField(default=False, verbose_name='Avez-vous des problèmes de santé?')),
                ('health_problem_description', models.TextField(blank=True, null=True, verbose_name='Description des problèmes de santé')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse de résidence')),
                ('nic', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de CNI')),
                ('niu', models.CharField(blank=True, max_length=20, null=True, verbose_name="Numéro d'Identification Unique")),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'urgence - Nom")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Contact d'urgence - Téléphone")),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Contact d'urgence - Email")),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name="Contact d'urgence - Relation")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lecturers/photos/', verbose_name='Photo de profil')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='lecturers/signatures/', verbose_name='Signature')),
                ('highest_diploma_obtained', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dernier diplôme obtenu')),
                ('external_password_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Mot de passe (portail enseignant)')),
                ('external_password_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du mot de passe')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name="Date de vérification de l'email")),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='Date dernière connexion')),
                ('favorite_subjects', models.ManyToManyField(blank=True, related_name='favorite_lecturers', to='academic.course', verbose_name='Matières préférées')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
