# Generated by Django 4.2.28 on 2026-05-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='favorite_subjects',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='lecturers/cvs/', verbose_name='Curriculum Vitae'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='highest_diploma_obtained',
            field=models.CharField(blank=True, choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=100, null=True, verbose_name='Dernier diplôme obtenu'),
        ),
    ]
