# Generated by Django 4.2.28 on 2026-05-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_remove_lecturer_favorite_subjects_lecturer_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='recruitment_step',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Dernière étape de recrutement complétée'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='recruitment_submitted',
            field=models.BooleanField(default=False, verbose_name='Dossier de candidature soumis'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='recruitment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission du dossier'),
        ),
    ]
