# Generated by Django 4.2.28 on 2026-05-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0003_lecturer_recruitment_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Enseignant permanent ?'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('hired', 'Recruté'), ('refused', 'Refusé'), ('licensed', 'Licencié'), ('resigned', 'Démissionnaire')], default='draft', max_length=20, verbose_name='Statut du dossier'),
        ),
    ]
