# Generated by Django 4.2.28 on 2026-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0004_lecturer_is_permanent_lecturer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='can_be_resubmitted',
            field=models.BooleanField(default=True, verbose_name='Peut être resoumis (après refus)'),
        ),
    ]
