# Generated by Django 4.2.28 on 2026-06-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0005_lecturer_can_be_resubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Adresse de résidence'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='health_problem_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description des problèmes de santé'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='nic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de CNI'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='niu',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Numéro d'Identification Unique"),
        ),
    ]
